# Generated by Django 3.2.3 on 2021-05-25 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='Deleted Date')),
                ('deleted_by', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Fac_IDNumber', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Comm_FacName', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('Zone', models.CharField(max_length=100)),
                ('Region_Code', models.CharField(max_length=100)),
                ('District_Code', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Council_Code', models.CharField(max_length=100)),
                ('Council', models.CharField(max_length=100)),
                ('Ward', models.CharField(max_length=100)),
                ('Village', models.CharField(max_length=100)),
                ('FacilityTypeGroupCode', models.CharField(max_length=100)),
                ('FacilityTypeGroup', models.CharField(max_length=100)),
                ('FacilityTypeCode', models.CharField(max_length=100)),
                ('FacilityType', models.CharField(max_length=100)),
                ('OwnershipGroupCode', models.CharField(max_length=100)),
                ('OwnershipGroup', models.CharField(max_length=100)),
                ('OwnershipCode', models.CharField(max_length=100)),
                ('Ownership', models.CharField(max_length=100)),
                ('OperatingStatus', models.CharField(max_length=100)),
                ('Latitude', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('RegistrationStatus', models.CharField(max_length=100)),
                ('OpenedDate', models.CharField(max_length=100)),
                ('CreatedAt', models.CharField(max_length=100)),
                ('UpdatedAt', models.CharField(max_length=100)),
                ('ClosedDate', models.CharField(max_length=100)),
                ('OSchangeOpenedtoClose', models.CharField(max_length=100)),
                ('OSchangeClosedtoOperational', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
