# Generated by Django 3.2.3 on 2021-05-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20210525_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='PostorUpdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
