# Generated by Django 3.2.3 on 2021-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_auto_20210525_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='ClosedDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
